### PR TITLE
Update to 1.19.4

### PR DESCRIPTION
**Pull request by Jikoo**
* Add support for 1.19.4
* Drop support for 1.19/1.19.1

I don't have time to test this this morning. If anyone is really chomping at the bit to update their server, dev builds can be found in completed [CI runs](https://github.com/Jikoo/OpenInv/actions/workflows/ci.yml). Select the run you want, scroll down to the bottom, download and unzip `dist`. Otherwise, expect a release this afternoon.

### CODE REVIEW

**Comment by molor** [comment]
Hello! In case this issue is caused by OI, I'll leave it here: https://github.com/EngineHub/WorldGuard/issues/1987

**Comment by Jikoo** [comment]
> Last line in server logs is `[com.lishid.openinv.internal.v1_19_R3.OpenPlayer] Failed to save player data for Player: Saving entity NBT`

This is super important. It looks either loading or saving changed a little. I'm assuming this means reading the player's NBT no longer sets the player's current position, though I'll need to dive into it some more.

**Comment by Jikoo** [comment]
Okay, no, nothing has changed here.
```Java
if (this instanceof ServerPlayer) {
  Server server = Bukkit.getServer();
  World bworld = null;
  String worldName = nbttagcompound.getString("world");
  if (nbttagcompound.contains("WorldUUIDMost") && nbttagcompound.contains("WorldUUIDLeast")) {
    UUID uid = new UUID(nbttagcompound.getLong("WorldUUIDMost"), nbttagcompound.getLong("WorldUUIDLeast"));
    bworld = server.getWorld(uid);
  } else {
    bworld = server.getWorld(worldName);
  }

  if (bworld == null) {
    bworld = ((CraftServer)server).getServer().getLevel(Level.OVERWORLD).getWorld();
  }

  ((ServerPlayer)this).setLevel(bworld == null ? null : ((CraftWorld)bworld).getHandle());
}
```

The only way to get this to occur is if you have no overworld worlds and the world the player was already in does not exist. There's... really not a lot I can do about this. Either OI can attempt to recover, which will result in players moving to the default world after being opened, or OI can report those players nonexistent until they log in and the server decides what it wants to do with them.

**Comment by molor** [comment]
I can reproduce this and send you stacktrace if needed and you tell me how to force OI to display it — maybe this can make the issue more clear

**Comment by molor** [comment]
The only change in my current world list is an plugin-created NORMAL/NORMAL world `minecraft:future`. Other vanilla worlds (`minecraft:overworld` etc.) isn't touched. But `future` sometimes gets removed (entire world folder) to generate a new one, so its UUID sometimes changes — if that's important then now you know :D

Okay, I'll be waiting for Paper team to update/fix/reply.

**Comment by molor** [comment]
Now with latest Paper & OI only this appears in console if I use `/oi` with random player name (idk how the search works but it's always find some1 old XD)
```
[com.lishid.openinv.internal.v1_19_R3.PlayerDataManager] Encountered null world while loading kaneuss
```

**Comment by molor** [comment]
(can you also please change `[com.lishid.openinv.internal.v1_19_R3.PlayerDataManager]` to `[OpenInv] [PlayerDataManager]` or even better to `[OpenInv]`?)

**Comment by Jikoo** [comment]
> idk how the search works

Search uses a [Jaro-Winkler](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance) string metric ignoring capitalization. Best match is used for whatever you provide as an argument. It used to use a [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) which was available through some ancient bundled library, but that often resulted in wild inaccuracies for short names.

> (can you also please change `[com.lishid.openinv.internal.v1_19_R3.PlayerDataManager]` to `[OpenInv] [PlayerDataManager]` or even better to `[OpenInv]`?)

I know this doesn't line up with how Bukkit plugins usually do logging, but I generally try to use vanilla as a guide for working with server internals. I am way more concerned about the fact that you're running into the issue than how the logging compares to what you're used to seeing.

**Comment by alexchandel** [comment]
Is it really too much to support all of 1.19, that is, all of the current major version?  Does the API really change that much?  It makes it hard to update from say 1.19.2 to 1.19.4 when plugins don't support both versions.

**Comment by Jikoo** [comment]
Yes. Each NMS revision is additional maintenance. Backporting fixes is a boring, menial chore, and the more places I have to do it the less motivated I am to bother at all. See for example https://github.com/Jikoo/OpenInv/commit/454467c20ee00fbba0b51959a3bb93f80b87a51a - this is not worth my time. If you can't upgrade your server in a reasonable amount of time, you can always compile your own bridge or just follow standard safe procedures and create a copy of your live server with updated plugins, then apply the plugins and server to the live server when you have confirmed it to be functional.

Also, pretty sure 1.19.2 had the same NMS revision as 1.19.3, so either you already were locked into a very specific version of OI by Spigot not bumping the version or you already could be using 4.3.0 and have the bridge functionality you're asking for.

**Pull request merged**
