### PR TITLE
Add support for 1.20.4

### PR DESCRIPTION
**Pull request by Jikoo**
* Add support for 1.20.4
* Drop support for 1.20

Per usual, use at your own risk and report any issues, please and thank you.

### CODE REVIEW

**Comment by Jikoo** [comment]
A note for interested parties: it's my finals week and I also have just finished dealing with some major IRL changes. I'm not going to be testing this until the end of the week, I do not have time. If you're willing to take it on or need it now, please grab the build and let me know how it goes.

**Comment by lrj1818** [comment]
> A note for interested parties: it's my finals week and I also have just finished dealing with some major IRL changes. I'm not going to be testing this until the end of the week, I do not have time. If you're willing to take it on or need it now, please grab the build and let me know how it goes.

Hey How Do You Grab A Build? Or Can You Send The Jar File Or A Tutorial On How To Get The Build If Possible.

**Comment by Jikoo** [comment]
> Hey How Do You Grab A Build? Or Can You Send The Jar File Or A Tutorial On How To Get The Build If Possible.

Each successful run has an artifact "dist" attached, which is the full binary. The latest run for this branch is here: https://github.com/Jikoo/OpenInv/actions/runs/7152644165

**Comment by molor** [comment]
Can some1 also test it and report the result?

**Comment by Aurelien30000** [comment]
Seems to be working fine for a basic usage! Thanks :D

**Pull request merged**
