### PR TITLE
fix resolutions for items so mipmap level isnt lowered

### PR DESCRIPTION
**Pull request by Boy0000**
18x18 and 18x36 is not divisible by 4, so the mipmap level is lowered causing blurry textures
this just rescales them to 16x16 and 16x32 to fix this
```
[14:59:38] [Worker-Main-84/WARN]:
Texture openinv:item/not_a_slot with size 18x18 limits mip level from 4 to 1
[19:24:32] [Worker-Main-106/WARN]:
Texture openinv:item/crafting_output with size 18x36 limits mip level from 4 to 1
```

### CODE REVIEW

**Comment by Jikoo** [comment]
Ah, things I don't experience as a serial low detail user, whoops. The multiples of 18 were important to line up with existing inventories when stretched out. Will this work out the same? Do we need to adjust the render size or should we consider doubling the pixel counts to 36x36/36x72 so they have a multiple of 4 and render the same way they currently do?

Sorry if the questions are silly, I'm afraid I'm horribly inexperienced with resource packs and this all was kludged together by combing over the wiki and making mistakes for hours on end.

**Comment by Boy0000** [comment]
Sorry for the late response, it seems to remain just fine when testing it locally

image

**Comment by Boy0000** [comment]
pushed a fix that adjusts the output texture abit
image

**Comment by Jikoo** [comment]
Awesome, thank you!

An aside: I see you're using a custom pack that removes the inventory name, You should be able to set `openinv.container.inventory.suffix="Inventory - %s"` in the language file to replace the missing identifier if you want it.

**Pull request merged**
